name: inline_snapshot
description: |
  Inline snapshot testing for Dart.
  Allows updating expected results based on actual results.
version: 1.0.1
repository: https://github.com/ktanaka101/dart-inline-snapshot

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  analyzer: ^5.3.1
  codemod: ^1.0.11
  stack_trace: ^1.11.0
  test: ^1.16.0

dev_dependencies:
  lints: ^2.0.0
  uuid: ^3.0.7
  path: ^1.8.3
